import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Footer() {
  return (
    <div>
      <Head>
        <title>Doktori Napok 2021</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <footer className={styles.footer}>
        <div>
          <p>Szegedi Tudományegyetem</p>
          <p>6720 Szeged, Dugonics tér 13.</p>
          <p>Központi telefonszám: (+36-62) 544-000</p>
          <p>Központi fax: (+36-62) 546-371</p>
        </div>
        <p className={styles.hideOnMobile}>
          (C) 2021 Szegedi Tudományegyetem. Minden jog fenntartva.
        </p>
      </footer>
    </div>
  );
}
