import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Doktori Napok 2021</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          DOKTORI NAPOK <span>2021</span>
        </h1>

        <p className={styles.description}>
          Országos Doktori Konferencia <br /> Szeged | 2021. május 18-21.
        </p>

        <p className={styles.details}>
          Idén kerül először megrendezésre a Doktori Napok nevű
          multidiszciplináris országos doktori konferencia. Az esemény célja,
          hogy a magyarországi egyetemek doktori programjaiban tanuló hallgatók
          számára lehetőséget biztosítson arra, hogy szakmai közönség előtt
          mutathassák be kutatási témáikat. <br />
          <br /> Várjuk szeretettel minden olyan aktív kutatással rendelkező PhD
          hallgató jelentkezését, aki szeretné bemutatni meglévő eredményeit és
          aki szívesen kipróbálná magát előadói szerepben.
        </p>

        <div className={styles.grid}>
          <Link href="/tudnivalok">
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Tudnivalók &rarr;</h2>
              <p>A legfontosabb tudnivalók a konferenciával kapcsolatban.</p>
            </a>
          </Link>

          <Link href="/jelentkezes">
            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Jelentkezés &rarr;</h2>
              <p>A jelenkezés módja, menete és az elbírálás folyamata.</p>
            </a>
          </Link>

          <Link href="/program">
            <a
              href="https://github.com/vercel/next.js/tree/master/examples"
              className={styles.card}
            >
              <h2>Program &rarr;</h2>
              <p>A 2021. évi Doktori Napok részletes programja.</p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
}
