import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Application() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Doktori Napok 2021</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>
        DOKTORI NAPOK <span>2021</span>
      </h1>

      <p className={styles.description}>
        Országos Doktori Konferencia <br /> Szeged | 2021. május 18-21.
      </p>
      <div className={styles.details}>
        <p className={styles.subtitle}>Jelentkezés módja</p>
        <p>
          Jelentkezni az angol vagy magyar nyelvű előadások angol nyelvű
          kivonatával (500 szó) lehet 2021. április 12.-ig, a pályázó
          egyetemének tanulmányi osytályán keresztül. A jelentkezések
          elfogadásáról április 30-ig küldünk értesítést. Egy hallgató
          ugyanarról a kutatóhelyről csak egy előadásnak lehet első szerzője. A
          bejelentett előadásoknak legfeljebb két szerzője és két témavezetője
          lehet.
        </p>
        <p className={styles.subtitle}>Absztrakt követelményei</p>
        <p>
          Az absztraktnak tartalmaznia kell a felhasznált módszerek és a kapott
          adatok részletes leírását, hossza maximum 500 szó lehet. Az absztrakt
          felépítése: bevezetés, célkitűzés, módszer, eredmények,
          következtetések. Javasoljuk az előírt karakterszámon belül
          számszerűsített következtetések levonását. Esetismertetés nem
          fogadható el. Korábbi években előadott, tartalmilag azonos előadás nem
          adható be.
        </p>
        <p className={styles.subtitle}>Elbírálás menete</p>
        <p>
          A beérkezett összefoglalók a Doktori Napok elnökségének vezetése alatt
          álló szakmai bizottság előzetes bírálatán esnek át. Akik munkáját az
          összefoglalója alapján a szakmai bizottság bemutatásra nem fogadta el,
          értesítést küldünk. Azoknak a hallgatóknak, akiknek pályamunkája
          elfogadást nyert április 30-ig küldünk értesítést.
        </p>
      </div>
      <Link href="/">
        <a className={styles.back}>&larr; Vissza a főoldalra</a>
      </Link>
    </div>
  );
}
