import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Schedule() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Doktori Napok 2021</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>
        DOKTORI NAPOK <span>2021</span>
      </h1>
      <p className={styles.description}>
        Országos Doktori Konferencia <br /> Szeged | 2021. május 18-21.
      </p>
      <div className={styles.details}>
        <p className={`${styles.subtitle} ${styles.programDay}`}>
          Május 18. | KEDD
        </p>
        <p className={styles.presentation}>
          <b>9:00-9:45:</b> Prof. Dr. Szomora Zsolt, a konferencia fővédnöke
          ünnepélyes megnyitó beszédet tart a nagyelőadóban majd ismerteti a
          konferencia menetét.
        </p>
        <p className={styles.presentation}>
          <b>9:45-10:00:</b> Szünet.
        </p>
        <p className={styles.presentation}>
          <b>10:00-11:45:</b> dr. Sáros Luca, a SOTE-ÁOK másodéves doktorandusz
          hallgatójának előadása a magyar orvostudomány technikai megújulásának
          lehetőségeiről, potenciális partnereiről, és a nemzetközi
          tapasztalatairól. (Doktori képzése folyamán témavezetője: Dr. Mérei
          Ildikó)
        </p>
        <p className={styles.presentation}>
          <b>11:45-12:45:</b> Ebédszünet.
        </p>
        <p className={styles.presentation}>
          <b>12:45-14:15:</b> Herczeg Balázs a BME-VBK harmadéves doktorandusz
          hallgatójának előadása a grafének felhasználásáról a gyógyszeriparban.
          (Doktori képzése folyamán témavezetője: Nagy László)
        </p>
        <p className={styles.presentation}>
          <b>14:15-14:30:</b> Szünet.
        </p>
        <p className={styles.presentation}>
          <b>14:30-16:00:</b> dr. Sáros Luca és Herczeg Balázs
          panelbeszélgetése. Moderátor: Dargó Gyula.
        </p>
        <p className={styles.presentation}>
          <b>16:00-16:15:</b> Szünet.
        </p>
        <p className={styles.presentation}>
          <b>16:15-17:00:</b> Dr. Nagy Zoltán Zsolt összefoglalója az
          elhangzottakról, és zárás.
        </p>
        <p className={`${styles.subtitle} ${styles.programDay}`}>
          Május 19. | SZERDA
        </p>
        <p className={styles.presentation}>
          <b>9:00-9:45:</b> Dr. Koller Boglárka megnyitója a szerdai
          előadásokról, továbbá a panelbeszélgetés menetéről, és tartalmáról.
        </p>
        <p className={styles.presentation}>
          <b>9:45-10:00:</b> Szünet.
        </p>
        <p className={styles.presentation}>
          <b>10:00-11:45:</b> Győrfy Márton, az SZTE-BTK harmadéves doktorandusz
          hallgatójának előadása Magyarország regionális inegrációjának
          jövőjéről orosz-, és kínabarát szemptonok alapján. (Doktori képzése
          folyamán témavezetője: Dr. Halász Iván)
        </p>
        <p className={styles.presentation}>
          <b>11:45-12:45:</b> Ebédszünet.
        </p>
        <p className={styles.presentation}>
          <b>12:45-14:15:</b> Domján Bálint az NKE-HDT első éves doktorandusz
          hallgatójának előadása az orosz információs hadviselés alakulásáról az
          elmúlt öt évben. (Doktori képzése folyamán témavezetője: Prof. dr.
          Csikány Tamás Péter ezredes).
        </p>
        <p className={styles.presentation}>
          <b>14:15-14:30:</b> Szünet.
        </p>
        <p className={styles.presentation}>
          <b>14:30-16:00:</b> Győrfy Márton és Domján Bálint panelbeszélgetése.
          Moderátor: Dr. Kutasi Gábor.
        </p>
        <p className={styles.presentation}>
          <b>16:00-16:15:</b> Szünet.
        </p>
        <p className={styles.presentation}>
          <b>16:15-17:00:</b> Dr. Patyi András összefoglalója az
          elhangzottakról, és zárás.
        </p>
        <p className={`${styles.subtitle} ${styles.programDay}`}>
          Május 20. | CSÜTÖRTÖK
        </p>
        <p className={styles.presentation}>
          <b>9:00-9:45:</b> Prof.Dr. Aczél Petra megnyitója a csütörtöki
          előadásokról, továbbá a panelbeszélgetés menetéről, és tartalmáról.
        </p>
        <p className={styles.presentation}>
          <b>9:45-10:00:</b> Szünet.
        </p>
        <p className={styles.presentation}>
          <b>10:00-11:45:</b> Kiss Hanna, a BCE-TK negyedéves doktorandusz
          hallgatójának előadása az Európai Unió gazdasági-, és politikai
          uniójának erősítéséről az Európán kívüli nagyhatalmakkal szemben.
          (Doktori képzése folyamán témavezetője: Dr. Ács György)
        </p>
        <p className={styles.presentation}>
          <b>11:45-12:45:</b> Ebédszünet.
        </p>
        <p className={styles.presentation}>
          <b>12:45-14:15:</b> Szász László az ELTE-TÁTK első éves doktorandusz
          hallgatójának előadása az Egyesült Államok nemzetközi szerepéről a
          COVID járvány, és az amerikai újbaloldal felemelkedésének fényében.
          (Doktori képzése folyamán témavezetője: Majtényi Balázs)
        </p>
        <p className={styles.presentation}>
          <b>14:15-14:30:</b> Szünet.
        </p>
        <p className={styles.presentation}>
          <b>14:30-16:00:</b> Kiss Hanna és Szász László panelbeszélgetése.
          Moderátor: Dr. Adorján Csaba.
        </p>
        <p className={styles.presentation}>
          <b>16:00-16:15:</b> Szünet.
        </p>
        <p className={styles.presentation}>
          <b>16:15-17:00:</b> Amati Gergely összefoglalója az elhangzottakról,
          és zárás.
        </p>
        <p className={`${styles.subtitle} ${styles.programDay}`}>
          Május 21. | PÉNTEK
        </p>

        <p className={styles.presentation}>
          <b>9:00-9:45:</b> Dr. Benkei-Kovács Balázs megnyitója a pénteki
          előadásról és a konferencia utolsó napjának menetéről.
        </p>
        <p className={styles.presentation}>
          <b>9:45-10:00:</b> Szünet.
        </p>
        <p className={styles.presentation}>
          <b>10:00-11:45:</b> Farkas Renáta a BGE-KVIK első éves doktorandusz
          hallgatójának előadása a magyarországi település-migráció jelenlegi
          alakulásáról a különböző régiók összehasonlításban. (Doktori képzése
          folyamán témavezetője: Dr. Egedy Tamás)
        </p>
        <p className={styles.presentation}>
          <b>11:45-12:45:</b> Ebédszünet.
        </p>
        <p className={styles.presentation}>
          <b>12:45-14:00:</b> Dr. Varga Norbert ünnepélyes záróbeszéde a
          konferenciáról, kitekintések az elhangzottakról, és konferencia zárás.
        </p>
      </div>

      <Link href="/">
        <a className={styles.back}>&larr; Vissza a főoldalra</a>
      </Link>
    </div>
  );
}
