import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Info() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Doktori Napok 2021</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>
        DOKTORI NAPOK <span>2021</span>
      </h1>

      <p className={styles.description}>
        Országos Doktori Konferencia <br /> Szeged | 2021. május 18-21.
      </p>
      <div className={styles.details}>
        <p className={styles.subtitle}>Bemutatkozás</p>
        <p>
          Az Magyar Tudományos Akadémia jubileumi programsorozata részeként idén
          először megrendezésre kerül a Doktori Napok. A konferencia az Új
          Nemzeti Kiválósági Program hivatalos rendezvénye, amelyen
          doktoranduszok, doktorjelöltek és posztdoktorok mutatják be tudományos
          eredményeiket. Az esemény célja, hogy lehetőséget adjon eddigi
          eredmények bemutatására, egyben az előadói szerep gyakorlására,
          prezentációs technikák fejlesztésére.
        </p>
        <p className={styles.subtitle}>A konferencia időpontja és helyszíne</p>
        <p>
          2021. május 17-21. Szegedi Tudományegyetem, Konferencia Központ,
          Nagyelőadó (Szeged, Dugonics tér 13.)
        </p>
        <p className={styles.subtitle}>Absztrakt leadás határideje</p>
        <p>
          2021. április 12. (kizárólag angol nyelvű absztraktot lehet
          beküldeni,az absztraktokból online absztraktfüzet készül)
        </p>
        <p className={styles.subtitle}>COVID tudnivalók</p>
        <p>
          Az esemény szervezése során minden járványügyi intézkedést fokozottan
          betartunk. Ennek értelmében a nagyteremben 50 főnél többen nem
          tartózkodhatnak egyszerre. A konferencia helyszínén több
          kézfertőtlenítő állomást is kihelyezünk, illetve minden szünetben
          szellőztetünk. <br />
          <br /> Azoknak, akik védettségüket hatósági igazolvány bemutatásával
          igazolni tudják nem kell maszkot viselniük a rendezvényen. A
          koronavírus elleni védettség igazolása a védettségi igazolvány
          bemutatásával történik, a védettség tényének ellenőrzése a nagyterem
          bejáratánál történik. A nagytermen kívül maszk viselése minden
          résztvevő számára kötelező.
        </p>
        <p className={styles.subtitle}>Neptun ügyintézés</p>
        <p>
          A konferencia kötelezően választható (KV-kóddal ) PhD kurzusként
          meghirdetésre kerül a Neptunban. A február 1-14 között a regisztrációs
          időszakban a Neptun-on keresztül felvehető, február 14 után már csak a
          tanulmányi ügyintéző segítségével vehető fel. (1 kreditpont a
          részvétel absztrakt nélkül, 2 kreditpont a poszter vagy oral
          szekcióban történő részvétel, 3 kreditpont szekcíó díjazott)
        </p>
        <p className={styles.subtitle}>Utazás, szállás</p>
        <p>
          A konferenciára való érkezést és szállást minden hallgató egyénileg
          intézi. Amennyiben a járvány miatt bármelyik hallgató nehézségekbe
          ütközne ezen a téren, kérjük egyetemének tanulmányi osztályán
          keresztül vegye fel a kapcsolatot a szervezőkkel, akik igyekeznek
          valamilyen megoldást problémára.
        </p>
        <p className={styles.subtitle}>Publikálás</p>
        <p>
          A konferencia előadói által készített tanulmányokból a Szegedi
          Tudományegyetem egy lektorált tanulmánykötetet szerkeszt, amelybe a
          felkért lektorok és szerkesztők által elfogadott, tudományos normáknak
          eleget tevő tanulmányok kerülhetnek bele. A Doktori Napok konferencia
          anyaga egy ISBN számmal ellátott digitális konferencia kötetben a SZTE
          könyvek sorozatán belül jelenik meg. A publikációkkal kapcsolatos
          szerkesztési alapelveket a konferencia után fogjuk megküldeni.
        </p>
        <p className={styles.subtitle}>Angolul is előadhatok?</p>
        <p>
          A poszter vagy a szóbeli prezentációk nyelve magyar és angol is lehet.
          A választott nyelvet kérjük, hogy jelentkezés során, az absztrakt
          feltöltésekor jelöljék meg.
        </p>
        <p className={styles.subtitle}>
          Külföldi egyetemről is jelentkezhetek?
        </p>
        <p>
          A programon a határontúli társegyetemek hallgatói, illetve külföldi
          vendéghallgatók is részt vehetnek.
        </p>
      </div>
      <Link href="/">
        <a className={styles.back}>&larr; Vissza a főoldalra</a>
      </Link>
    </div>
  );
}
